# 🔢 Introducción a NumPy

**NumPy (Numerical Python)** es una librería esencial para el cálculo numérico en Python.  
Proporciona estructuras de datos eficientes (los **arrays**) y operaciones matemáticas optimizadas que permiten realizar cálculos **vectorizados** de forma rápida.

A diferencia de las listas comunes, los arrays de NumPy ocupan menos memoria y ejecutan operaciones de manera más eficiente, aprovechando la computación en bajo nivel.


In [2]:
# Importar NumPy
import numpy as np

# Versión instalada
np.__version__


'2.3.3'

## 📦 Creación de arrays

El objeto central de NumPy es el **ndarray** (N-dimensional array).

Podemos crearlos a partir de listas o usando funciones integradas.


In [3]:
# Crear un array a partir de una lista
lista = [1, 2, 3, 4, 5]
arr = np.array(lista)

print("Array:", arr)
print("Tipo:", type(arr))
print("Dimensiones:", arr.ndim)
print("Forma:", arr.shape)
print("Tipo de datos:", arr.dtype)


Array: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Dimensiones: 1
Forma: (5,)
Tipo de datos: int64


## 🧮 Creación de arrays comunes

NumPy incluye funciones para generar arreglos con distintos patrones numéricos.


In [4]:
print("Array de ceros:\n", np.zeros((2, 3)))
print("\nArray de unos:\n", np.ones((2, 3)))
print("\nRango de números:\n", np.arange(0, 10, 2))
print("\nNúmeros equiespaciados:\n", np.linspace(0, 1, 5))
print("\nMatriz identidad:\n", np.eye(3))


Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array de unos:
 [[1. 1. 1.]
 [1. 1. 1.]]

Rango de números:
 [0 2 4 6 8]

Números equiespaciados:
 [0.   0.25 0.5  0.75 1.  ]

Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 🔢 Acceso e indexación

Podemos acceder a los elementos de un array de manera similar a las listas,  
pero con más control cuando se trabaja con matrices multidimensionales.


In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Array:\n", arr)
print("Elemento (0,1):", arr[0, 1])  # fila 0, columna 1
print("Primera fila:", arr[0])
print("Segunda columna:", arr[:, 1])


Array:
 [[10 20 30]
 [40 50 60]]
Elemento (0,1): 20
Primera fila: [10 20 30]
Segunda columna: [20 50]


## ⚙️ Operaciones vectorizadas

A diferencia de las listas, NumPy permite realizar **operaciones matemáticas directamente sobre los arrays**, sin usar bucles.


In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Suma:", a + b)
print("Resta:", a - b)
print("Producto:", a * b)
print("División:", a / b)
print("Potencia:", a ** 2)


Suma: [11 22 33 44]
Resta: [ -9 -18 -27 -36]
Producto: [ 10  40  90 160]
División: [0.1 0.1 0.1 0.1]
Potencia: [ 1  4  9 16]


## 🧠 Comparación con listas

Veamos la diferencia entre usar listas nativas de Python y arrays de NumPy.


In [7]:
import time

# Crear listas y arrays grandes
L = list(range(1_000_000))
A = np.arange(1_000_000)

# Suma con listas (más lenta)
inicio = time.time()
L2 = [x * 2 for x in L]
print("Tiempo con listas:", round(time.time() - inicio, 4), "s")

# Suma con NumPy (más rápida)
inicio = time.time()
A2 = A * 2
print("Tiempo con NumPy:", round(time.time() - inicio, 4), "s")


Tiempo con listas: 0.0878 s
Tiempo con NumPy: 0.005 s


## 🧮 Operaciones estadísticas

NumPy tiene funciones predefinidas para cálculos comunes: media, desviación estándar, mínimo, máximo, etc.


In [ ]:
valores = np.array([10, 15, 20, 25, 30])

print("Media:", np.mean(valores))
print("Desviación estándar:", np.std(valores))
print("Mínimo:", np.min(valores))
print("Máximo:", np.max(valores))
print("Suma total:", np.sum(valores))


## 🧩 Operaciones matriciales

Los arrays 2D pueden usarse como matrices, lo que permite realizar multiplicaciones, transpuestas y determinantes.


In [ ]:
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])

print("Multiplicación elemento a elemento:\n", M1 * M2)
print("\nProducto matricial:\n", np.dot(M1, M2))
print("\nTranspuesta de M1:\n", M1.T)


## 🔄 Cambiar forma y dimensiones

Podemos transformar la forma de un array con `reshape()`, sin cambiar su contenido.


In [ ]:
arr = np.arange(1, 13)
print("Array original:", arr)

matriz = arr.reshape(3, 4)
print("\nMatriz 3x4:\n", matriz)

vector = matriz.flatten()
print("\nConvertido de nuevo a 1D:", vector)


## 🧩 Ejemplo práctico: promedio de columnas

Supongamos que tenemos los puntajes de tres estudiantes en cuatro asignaturas,  
y queremos calcular el promedio por asignatura.


In [8]:
notas = np.array([
    [3.5, 4.0, 3.8, 4.2],
    [4.1, 3.9, 4.5, 4.3],
    [3.7, 4.2, 4.0, 3.8]
])

promedios = np.mean(notas, axis=0)  # promedio por columna
print("Promedio por asignatura:", promedios)


Promedio por asignatura: [3.76666667 4.03333333 4.1        4.1       ]


## ⚡ Ejemplo: norma euclidiana

NumPy también incluye funciones para cálculos vectoriales, como la **norma (longitud)** de un vector.


In [ ]:
v = np.array([3, 4])
norma = np.linalg.norm(v)

print("Vector:", v)
print("Norma euclidiana:", norma)


## 🧮 Otras operaciones útiles

- `np.max`, `np.min`, `np.argmax`, `np.argmin`  
- `np.sort` → ordena elementos  
- `np.unique` → elimina duplicados  
- `np.concatenate` → une arrays


In [ ]:
a = np.array([1, 3, 5, 3, 1])
b = np.array([7, 9])

print("Array ordenado:", np.sort(a))
print("Valores únicos:", np.unique(a))
print("Índice del máximo:", np.argmax(a))
print("Concatenación:", np.concatenate((a, b)))


## 🧩 Actividad práctica

1. Crea una matriz 3×3 con números enteros del 1 al 9.  
2. Calcula:
   - La suma de cada fila.
   - El promedio de cada columna.
   - La matriz transpuesta.
   - La norma de cada fila.

> *Tip:* Usa `np.sum(..., axis=1)` y `np.mean(..., axis=0)`.


In [9]:
# Tu solución aquí 👇
mat = np.arange(1, 10).reshape(3, 3)

print("Matriz original:\n", mat)
print("Suma por fila:", np.sum(mat, axis=1))
print("Promedio por columna:", np.mean(mat, axis=0))
print("Transpuesta:\n", mat.T)
for i in range(mat.shape[0]):
    print(f"Norma de la fila {i+1}:", np.linalg.norm(mat[i]))


Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma por fila: [ 6 15 24]
Promedio por columna: [4. 5. 6.]
Transpuesta:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Norma de la fila 1: 3.7416573867739413
Norma de la fila 2: 8.774964387392123
Norma de la fila 3: 13.92838827718412


## ✅ Conclusiones

- **NumPy** es la base de la computación científica en Python.  
- Permite trabajar con datos numéricos de manera **eficiente y vectorizada**.  
- Las operaciones son más rápidas y expresivas que con listas nativas.  
- Es el punto de partida para herramientas avanzadas como **Pandas**, **Matplotlib**, y **SciPy**.

En la siguiente sección veremos cómo manejar archivos para importar y exportar datos, preparando el terreno para trabajar con conjuntos de datos reales.
