# 🔄 Inversa y Transpuesta de una Matriz

En esta lección estudiaremos dos operaciones fundamentales del álgebra lineal:

- **La transpuesta:** reorganiza la matriz intercambiando filas por columnas.
- **La inversa:** deshace el efecto de una transformación lineal (si existe).

Ambas operaciones se utilizan constantemente en aplicaciones como:
- resolución de sistemas lineales,  
- transformaciones geométricas,  
- optimización,  
- estadística,  
- aprendizaje automático.

---

# 1. 📤 Transpuesta de una matriz

La **transpuesta** de una matriz $ A \in \mathbb{R}^{m \times n} $ es la matriz $A^T \in \mathbb{R}^{n \times m}$ obtenida al **intercambiar filas por columnas**.

$$
A =
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
\end{pmatrix}
\quad\Rightarrow\quad
A^T =
\begin{pmatrix}
a_{11} & a_{21} \\
a_{12} & a_{22} \\
a_{13} & a_{23} \\
\end{pmatrix}
$$

---

## ✔️ Propiedades de la transpuesta

1. $(A^T)^T = A$  
2. $(A + B)^T = A^T + B^T$  
3. $(\alpha A)^T = \alpha A^T$  
4. $(AB)^T = B^T A^T$  
5. $A \text{ es simétrica} \iff A = A^T$

---

## 💻 Ejemplo computacional

In [2]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("A^T =\n", A.T)

A^T =
 [[1 4]
 [2 5]
 [3 6]]



---

# 2. 🔁 Inversa de una matriz

Una matriz cuadrada $A \in \mathbb{R}^{n \times n}$ es **invertible** si existe una matriz $A^{-1}$ tal que:

$$
A A^{-1} = A^{-1} A = I.
$$

Solo las matrices **cuadradas y con determinante no nulo** son invertibles.

---

## ✔️ Condición de invertibilidad

Una matriz $A$ es invertible si y solo si:

1. $\det(A) \neq 0$
2. $\operatorname{rango}(A) = n$
3. Su sistema homogéneo tiene solo la solución trivial
4. Las columnas (o filas) son linealmente independientes
5. Representa una transformación lineal **bijectiva**

Todas estas condiciones son equivalentes.

---

## 📐 Fórmula para matrices (2 \times 2)

$$
A =
\begin{pmatrix}
a & b \\
c & d \\
\end{pmatrix}
\quad\Rightarrow\quad
A^{-1} = \frac{1}{ad - bc}
\begin{pmatrix}
d & -b \\
-c & a \\
\end{pmatrix}.
$$

---

## 💻 Inversa con Python

In [3]:
import numpy as np

A = np.array([[2, 1],
              [1, 3]])

A_inv = np.linalg.inv(A)

print("A^{-1} =\n", A_inv)
print("\nVerificación A * A^{-1} ≈ I:\n", A @ A_inv)

A^{-1} =
 [[ 0.6 -0.2]
 [-0.2  0.4]]

Verificación A * A^{-1} ≈ I:
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]



---

# 3. 🧠 Interpretación geométrica

## 🔹 TRANSPOSTA — “espejo algebraico”

* Intercambia filas ↔ columnas
* Cambia el dominio y codominio de la transformación lineal
* Es esencial en productos internos y proyecciones

Ejemplo:
$$
\mathbf{u}\cdot\mathbf{v} = u^T v
$$

---

## 🔹 INVERSA — “deshacer una transformación”

Si una matriz representa una transformación $T$:

$$
T(\mathbf{x}) = A\mathbf{x},
$$

entonces:

$$
T^{-1}(\mathbf{y}) = A^{-1}\mathbf{y}.
$$

Interpretaciones:

| Tipo de matriz | Interpretación geométrica            |
| -------------- | ------------------------------------ |
| Rotación       | La inversa rota en sentido contrario |
| Escala         | La inversa divide por el factor      |
| Cizalla        | La inversa deshace la deformación    |
| Reflejo        | La inversa es la misma matriz        |

---

# 4. 🔄 Relación entre transpuesta e inversa

Si $A$ es **ortogonal**, entonces:

$$
A^T = A^{-1}
$$

Propiedades:

* Las columnas de (A) forman una base ortonormal.
* Las rotaciones 2D y 3D son matrices ortogonales.
* Las matrices ortogonales **preservan longitudes y ángulos**.

---

## 💻 Ejemplo en código

In [4]:
Q = np.array([[0, -1],
              [1,  0]])  # rotación 90°

print("Q^T =\n", Q.T)
print("Q^{-1} =\n", np.linalg.inv(Q))  # debería coincidir

Q^T =
 [[ 0  1]
 [-1  0]]
Q^{-1} =
 [[ 0.  1.]
 [-1. -0.]]


---

# 5. 🧰 Implementaciones útiles


In [5]:
import numpy as np

def es_invertible(A):
    return not np.isclose(np.linalg.det(A), 0)

def inversa(A):
    if not es_invertible(A):
        raise ValueError("La matriz no es invertible.")
    return np.linalg.inv(A)

def es_ortogonal(A):
    return np.allclose(A.T @ A, np.eye(A.shape[0]))

def transpuesta(A):
    return A.T


---

# 6. 🧩 Ejercicios sugeridos de programación

### **1. Comprobador de ortogonalidad**

Implementa una función que reciba una matriz y verifique si cumple:

$$
A^T A = I
$$

---

### **2. Verificador de inversas**

Dado $A$, calcula:

* $A^{-1}$
* $A A^{-1}$
* $A^{-1} A$

y mide el error numérico.

---

### **3. Explorador geométrico**

Grafica en 2D o 3D:

* vectores antes de aplicar una matriz,
* vectores luego de aplicar:

  * la transpuesta,
  * la inversa.

---

### **4. Transformaciones encadenadas**

Pide al usuario ingresar matrices $A$ y $B$, calcula:

* $AB$
* $(AB)^{-1}$
* $B^{-1} A^{-1}$

y verifica:

$$
(AB)^{-1} = B^{-1} A^{-1}
$$

---

### **5. Matrices simétricas**

Genera matrices simétricas aleatorias y explora:

* si siempre son invertibles,
* cuándo no lo son,
* cómo se comporta la transpuesta.

---

# 📚 Conclusión

La **transpuesta** y la **inversa** son dos operaciones esenciales para entender las transformaciones lineales:

* La transpuesta reorganiza y revela simetrías.
* La inversa deshace los efectos de la transformación.
* Las matrices ortogonales combinan ambas operaciones en una sola.

> “La transpuesta es un espejo. La inversa, un camino de regreso.”

---

✅ **Fin del capítulo de matrices**.
Ahora estás lista para pasar al siguiente bloque del libro: **Transformaciones lineales** o cualquier otro capítulo que quieras desarrollar.