
# Taller Computacional Matrices

en esta sección usaremos python para calcular operaciones con matrices y vectores. Para las operaciones vectoriales y matriciales, usaremos la librería `numpy`.


## Generar una matriz

Generar la matriz debemos usar el comando `np.array` de la librería `numpy`, la matriz se debe ingresar como una lista de listas. Por ejemplo, para generar la matriz
$$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$$


In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]




**Crear un vector columna**

Ahora vamos a generar el vector columna

$$v=\begin{pmatrix} 1 \\ 2 \end{pmatrix},$$



In [2]:
import numpy as np

v = np.array([[1], [2]])

print(v)


[[1]
 [2]]


**Crear un vector fila**

$$w=\begin{pmatrix} 1 & 2 \end{pmatrix}$$


In [3]:
import numpy as np

w = np.array([[1, 2]])

print(w)


[[1 2]]



# Operaciones con matrices

Recuerde que para sumar dos matrices, estas deben tener la misma dimensión. Por ejemplo, si tenemos las matrices

$$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} \text{ y } B=\begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix},$$

la suma de estas matrices es




In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B

print(C)




[[ 6  8]
 [10 12]]


de la misma forma si queremos multiplicar una matriz por un escalar, por ejemplo, queremos multiplicar la matriz $A$ por el escalar $\alpha=2$:




In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
alpha = 2
C=alpha*A

print(C)




[[2 4]
 [6 8]]


Para la multiplicación de matrices podemos usar el comando `np.dot` de la librería `numpy` ó `@`. Por ejemplo, si tenemos las matrices

$$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} \text{ y } B=\begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix},$$

la multiplicación de estas matrices es



In [6]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C_dot = np.dot(A, B)
C_at = A @ B

print("Usando el comando np.dot",C_dot)
print("Usando el comando @",C_at)





Usando el comando np.dot [[19 22]
 [43 50]]
Usando el comando @ [[19 22]
 [43 50]]


## Ejericios

1. Seas $A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ y $B=\begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$, $X=\begin{pmatrix} 1 \\ 2 \end{pmatrix}$ y $Y=\begin{pmatrix} 3 \\ 4 \end{pmatrix}$, 

Calcule 
1. $A+B$, 

2. $A-B$, 

3. $A\cdot B$, 

4. $A\cdot X$, 

5. $A\cdot Y$

6. $X\cdot Y$.




In [7]:
# Puede resolver lo ejercicios aqui.

# Transpuesta de una matriz

Para calcula la transpuesta de una matriz, usamos el comando `np.transpose` de la librería `numpy`, o desúes de generar la matriz usamos el comando .T. Por ejemplo, si tenemos la matriz

$$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix},$$




In [8]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

A_transpuesta1 = np.transpose(A)

A_transpuesta2=A.T

print("usando el p comando mp.transpose",A_transpuesta1)
print("usando el segundo .T",A_transpuesta2)





usando el p comando mp.transpose [[1 3]
 [2 4]]
usando el segundo .T [[1 3]
 [2 4]]


# Determinante de una matriz

Para calcular el determinante de una matriz, usamos el comando `np.linalg.det` de la librería `numpy`. Por ejemplo, si tenemos la matriz

$$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix},$$





In [9]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

det_A = np.linalg.det(A)

print(det_A)




-2.0000000000000004


# Inversa de una matriz

Para calcular la inversa de una matriz, usamos el comando `np.linalg.inv` de la librería `numpy`. Por ejemplo, si tenemos la matriz

$$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix},$$



In [10]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

A_inversa = np.linalg.inv(A)

print(A_inversa)


[[-2.   1. ]
 [ 1.5 -0.5]]
